### ISSUE TITLE
Deck quick look numbers are wrong when loaded + crash

### ISSUE THREAD

**Issue by begna112** [DivvyCr/Balatro-Preview#15]
The quick look view shows a random number more or less than what is actually left. 
For example, King shows 2 left but only 1 is actually left while Queen shows 3 when there are actually 4 left. Nine shows 1 left when there are 4 left. 
![](https://i.ddy.moe/2024/04/Balatro_240405-074348.jpg)
![](https://i.ddy.moe/2024/04/Balatro_240405-074700.jpg)

This occurs even when loading or unloading mods if resuming a game where DV mods were loaded. I assume this data is stored in something about the current round.
![](https://i.ddy.moe/2024/04/Balatro_240405-074744.png)

I was able to recreate this consistently. 

Quitting and unloading all mods and resuming the current game/hand retains the bad numbers.

DVSimulate loaded without DVPreview: same issue.
DVPreview loaded without DVSimulate: crashes sometimes. If not, same issue.
![](https://i.ddy.moe/2024/04/Balatro_240405-080120.png)

**Comment by DivvyCr** [comment]
I see, this probably makes sense due to how I have to restore the game state after each simulation.

I'm working on a full rewrite right now, where this should not be possible. You can try a pre-release [here](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v2.0). It seems stable, but a few jokers may not be calculated correctly. Note that this pre-release does not simulate modded jokers.

Also, DVPreview cannot work without DVSimulate, so that crash is expected.

**Comment by begna112** [comment]
Just to be clear, this isn't exclusive to when reloading a game. It just also sticks around between reloads. 

I'll probably hold off unless you needed people to test. I'm trying out some modded joker packs at the moment.

**Comment by DivvyCr** [comment]
Seems to be an issue with Steamodded, so closing on that basis.
